const API_URL = (import.meta.env.VITE_API_URL || 'http://localhost:3000').replace(/\/$/, '');
const CSRF_PATH = '/api/v1/auth/csrf-token';
const UNSAFE = new Set(['POST', 'PUT', 'PATCH', 'DELETE']);
export interface ApiError extends Error { code?: string; status?: number; }
type ApiBody<T> = { data?: T; error?: { code?: string; message?: string } };
let csrfToken: string | null = null; let csrfInFlight: Promise<string> | null = null; let refreshInFlight: Promise<void> | null = null; let sessionExpiredHandler: (() => void) | null = null;
export function setSessionExpiredHandler(handler: (() => void) | null) { sessionExpiredHandler = handler; }
export function clearCsrfToken() { csrfToken = null; }
async function readBody<T>(response: Response): Promise<ApiBody<T>> { return (await response.json().catch(() => ({}))) as ApiBody<T>; }
function apiError<T>(response: Response, body: ApiBody<T>, fallback = 'Request failed'): ApiError { const error = new Error(body.error?.message || fallback) as ApiError; error.code = body.error?.code; error.status = response.status; return error; }
function isAuthPath(path: string) { return path === '/api/v1/auth/login' || path === '/api/v1/auth/register' || path === '/api/v1/auth/refresh' || path === CSRF_PATH; }
async function fetchCsrfToken(): Promise<string> { if (csrfToken) return csrfToken; if (!csrfInFlight) csrfInFlight = fetch(`${API_URL}${CSRF_PATH}`, { credentials: 'include', headers: { Accept: 'application/json' } }).then(async (response) => { const body = await readBody<{ csrfToken?: string; token?: string }>(response); const token = response.headers.get('X-CSRF-Token') || body.data?.csrfToken || body.data?.token; if (!response.ok || !token) throw apiError(response, body, 'Unable to obtain a CSRF token from the backend.'); csrfToken = token; return token; }).finally(() => { csrfInFlight = null; }); return csrfInFlight; }
async function refreshSession(): Promise<void> { if (!refreshInFlight) refreshInFlight = fetch(`${API_URL}/api/v1/auth/refresh`, { method: 'POST', credentials: 'include', headers: { 'Content-Type': 'application/json' } }).then(async (response) => { if (!response.ok) { const body = await readBody(response); throw apiError(response, body, 'Session expired.'); } }).finally(() => { refreshInFlight = null; }); return refreshInFlight; }
export async function apiRequest<T>(path: string, init: RequestInit = {}, retried = false): Promise<T> { const method = (init.method || 'GET').toUpperCase(); const unsafeCookieRequest = UNSAFE.has(method) && !isAuthPath(path); const headers = new Headers(init.headers); if (!headers.has('Content-Type') && init.body) headers.set('Content-Type', 'application/json'); if (unsafeCookieRequest) headers.set('X-CSRF-Token', await fetchCsrfToken()); const response = await fetch(`${API_URL}${path}`, { ...init, method, credentials: 'include', headers }); const body = await readBody<T>(response); if (response.status === 401 && !retried && !isAuthPath(path)) { try { await refreshSession(); } catch (error) { sessionExpiredHandler?.(); throw error; } return apiRequest<T>(path, init, true); } if (response.status === 403 && unsafeCookieRequest && !retried) { clearCsrfToken(); return apiRequest<T>(path, init, true); } if (!response.ok) throw apiError(response, body); return (body.data ?? body) as T; }
export const authApi = { login: (email: string, password: string) => apiRequest<{ user: BackendUser; requireMfa: boolean }>('/api/v1/auth/login', { method: 'POST', body: JSON.stringify({ email, password }) }), me: () => apiRequest<{ user: BackendUser; aal: 'aal1' | 'aal2' }>('/api/v1/auth/me'), refresh: () => refreshSession(), logout: () => apiRequest<{ message: string }>('/api/v1/auth/logout', { method: 'POST' }), challengeMfa: (token: string) => apiRequest<{ message: string }>('/api/v1/auth/mfa/challenge', { method: 'POST', body: JSON.stringify({ token }) }), setupMfa: () => apiRequest<{ secret: string; qrCode: string }>('/api/v1/auth/mfa/setup', { method: 'POST' }), verifyMfa: (token: string) => apiRequest<{ message: string }>('/api/v1/auth/mfa/verify', { method: 'POST', body: JSON.stringify({ token }) }) };
export interface BackendUser { id: string; email: string; fullName: string; status: string; mfaEnabled: boolean; avatarUrl?: string | null; }
export interface BackendTenant { membershipId: string; tenantId: string; tenantName: string; tenantSlug: string; status: string; }
export const tenantApi = { list: () => apiRequest<BackendTenant[]>('/api/v1/tenants'), current: (tenantId: string) => apiRequest<{ tenant: { id: string; name: string; slug: string }; membership: { id: string }; permissions: string[] }>('/api/v1/tenants/current', { headers: { 'X-Tenant-Id': tenantId } }), switch: (tenantId: string) => apiRequest<{ tenant: { id: string; name: string; slug: string }; membership: { id: string } }>('/api/v1/tenants/switch', { method: 'POST', body: JSON.stringify({ tenantId }) }) };
