import React, { useEffect, useState } from 'react';
import { Menu, X, ArrowRight } from 'lucide-react';

const NAV_LINKS = [{ label: 'Home', href: '/' }, { label: 'Platform', href: '/platform' }, { label: 'Security & Compliance', href: '/security' }, { label: 'Pricing', href: '/pricing' }];

export const LandingNavbar: React.FC<{ currentPath: string; navigate: (href: string) => void }> = ({ currentPath, navigate }) => {
  const [scrolled, setScrolled] = useState(false); const [open, setOpen] = useState(false);
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 20); window.addEventListener('scroll', onScroll); return () => window.removeEventListener('scroll', onScroll); }, []);
  const go = (href: string) => { setOpen(false); navigate(href); };
  return <header className={`sticky top-0 z-40 w-full transition-all ${scrolled ? 'backdrop-blur-md bg-[#FAF7F2]/90 border-b border-[#EBE6DD] py-3.5' : 'bg-[#FAF7F2]/80 border-b border-transparent py-5'}`}><div className="max-w-7xl mx-auto px-6 sm:px-12 flex items-center justify-between">
    <button type="button" onClick={() => go('/')} className="flex items-center gap-3 text-left" aria-label="AVENQUIS home"><span className="w-9 h-9 rounded-xl bg-[#113227] text-white flex items-center justify-center font-serif font-bold text-lg border border-[#235846]">A</span><span><span className="block text-xl sm:text-2xl font-serif font-black tracking-[0.16em] text-[#113227] uppercase leading-none">AVEN<span className="text-[#C58A3E] font-sans font-light tracking-normal mx-0.5">—</span>QUIS</span><span className="block text-[8.5px] uppercase tracking-[0.24em] font-bold text-[#8A5A18] mt-0.5">Firm Operating System</span></span></button>
    <nav className="hidden md:flex items-center gap-7 text-xs font-semibold uppercase tracking-wider" aria-label="Primary navigation">{NAV_LINKS.map((link) => <button key={link.href} type="button" onClick={() => go(link.href)} aria-current={currentPath === link.href ? 'page' : undefined} className={`py-1 relative group ${currentPath === link.href ? 'text-[#113227]' : 'text-[#4E5652] hover:text-[#113227]'}`}>{link.label}<span className={`absolute bottom-0 left-0 h-0.5 bg-[#C58A3E] transition-all ${currentPath === link.href ? 'w-full' : 'w-0 group-hover:w-full'}`} /></button>)}</nav>
    <div className="flex items-center gap-3"><button type="button" onClick={() => go('/sign-in')} className="px-4 py-2 rounded-full text-xs font-bold text-[#113227] hover:bg-[#E8E2D5] border border-[#DCD5C7]">Sign In</button><button type="button" onClick={() => setOpen(!open)} aria-expanded={open} aria-controls="mobile-nav" aria-label={open ? 'Close navigation' : 'Open navigation'} className="md:hidden p-2 text-stone-600 rounded-lg hover:bg-stone-100">{open ? <X className="w-5 h-5" /> : <Menu className="w-5 h-5" />}</button></div>
  </div>{open && <nav id="mobile-nav" className="md:hidden border-b border-[#EBE6DD] bg-[#FAF7F2] px-6 pt-4 pb-6 space-y-3 shadow-lg" aria-label="Mobile navigation">{NAV_LINKS.map((link) => <button key={link.href} type="button" onClick={() => go(link.href)} className="w-full text-left py-2 text-sm font-semibold text-[#1C1F1E] border-b border-[#F0EBE1]">{link.label}</button>)}<button type="button" onClick={() => go('/sign-in')} className="w-full py-2.5 rounded-xl bg-[#113227] text-white text-xs font-bold flex items-center justify-center gap-2">Sign In <ArrowRight className="w-3.5 h-3.5 text-[#C58A3E]" /></button></nav>}</header>;
};
