import React, { useState } from 'react';
import { ArrowLeft, CheckCircle2, FileText, Lock, Users } from 'lucide-react';

const tabs = ['Overview', 'Working papers', 'People'];

export function DemoWorkspace({ onExit }: { onExit: () => void }) {
  const [tab, setTab] = useState('Overview');
  return <div className="min-h-screen bg-[#F2EEE6] text-[#1C1F1E] p-4 sm:p-8"><div className="max-w-6xl mx-auto"><div className="flex flex-wrap items-center justify-between gap-4 mb-6"><div><p className="text-[10px] font-bold tracking-[0.25em] uppercase text-[#8A5A18]">Illustrative demo workspace</p><h1 className="mt-2 text-3xl sm:text-5xl font-serif font-bold text-[#113227]">Northstar &amp; Co. <span className="text-base font-sans font-bold text-[#8A5A18] align-middle">DEMO</span></h1><p className="mt-2 text-sm text-[#66706B]">Fictional data only • no production actions, regulator submissions, or external integrations</p></div><button type="button" onClick={onExit} className="flex items-center gap-2 rounded-full border border-[#DCD5C7] bg-white px-4 py-2 text-xs font-bold text-[#113227]"><ArrowLeft className="h-4 w-4" /> Exit demo</button></div><div className="rounded-3xl border border-[#DCD5C7] bg-white shadow-xl overflow-hidden"><div className="flex flex-wrap items-center gap-2 border-b border-[#EBE6DD] p-4">{tabs.map((item) => <button type="button" key={item} onClick={() => setTab(item)} className={`rounded-full px-4 py-2 text-xs font-bold ${tab === item ? 'bg-[#113227] text-white' : 'text-[#66706B] hover:bg-[#FAF7F2]'}`}>{item}</button>)}<span className="ml-auto flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-wider text-[#8A5A18]"><Lock className="h-3.5 w-3.5" /> Safe preview mode</span></div><div className="p-5 sm:p-8">{tab === 'Overview' && <div className="grid gap-4 sm:grid-cols-3"><DemoCard icon={<Users />} title="Team" value="4 fictional users" /><DemoCard icon={<FileText />} title="Working papers" value="12 illustrative files" /><DemoCard icon={<CheckCircle2 />} title="External actions" value="Disabled in demo" /></div>}{tab === 'Working papers' && <div className="space-y-3"><DemoRow title="WP-REV-01 • Revenue review" status="Illustrative draft" /><DemoRow title="WP-CASH-02 • Cash &amp; bank" status="Preview only" /><p className="pt-3 text-xs text-[#66706B]">Actions that would alter records or submit evidence are intentionally unavailable.</p></div>}{tab === 'People' && <div className="grid gap-3 sm:grid-cols-2"><DemoRow title="Mira Ahmed" status="Demo partner" /><DemoRow title="Rafi Khan" status="Demo manager" /><DemoRow title="Nadia Islam" status="Demo student" /><DemoRow title="Omar Chowdhury" status="Demo associate" /></div>}</div></div></div></div>;
}
function DemoCard({ icon, title, value }: { icon: React.ReactNode; title: string; value: string }) { return <div className="rounded-2xl border border-[#EBE6DD] bg-[#FAF7F2] p-5"><div className="flex items-center gap-2 text-[#8A5A18]">{React.cloneElement(icon as React.ReactElement<{ className?: string }>, { className: 'h-4 w-4' })}<span className="text-xs font-bold uppercase tracking-wider">{title}</span></div><p className="mt-5 text-lg font-serif font-bold text-[#113227]">{value}</p></div>; }
function DemoRow({ title, status }: { title: string; status: string }) { return <div className="flex items-center justify-between gap-4 rounded-2xl border border-[#EBE6DD] bg-[#FAF7F2] p-4"><span className="text-sm font-semibold text-[#113227]">{title}</span><span className="rounded-full bg-[#FCEFD9] px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-[#8A5A18]">{status}</span></div>; }
