import React, { useEffect, useRef, useState } from 'react';
import { Bot, Send, Sparkles, X } from 'lucide-react';
import { apiRequest } from '../../lib/api';
import { PET_ASSETS } from '../ai-pet/aiPetAssets';
import type { PetState } from '../ai-pet/aiPetState';
import type { UserSession } from '../../types';

interface Props { isOpen: boolean; onClose: () => void; currentUser: UserSession; onStateChange?: (state: PetState) => void; }
type Message = { id: string; sender: 'ai' | 'user'; text: string };
type PetResponse = { message: string; state: PetState; contextType: 'FIRM' | 'PLATFORM_ADMIN' };

export const AiAssistantDrawer: React.FC<Props> = ({ isOpen, onClose, currentUser, onStateChange }) => {
  const [input, setInput] = useState(''); const [messages, setMessages] = useState<Message[]>([]); const [state, setState] = useState<PetState>('IDLE'); const [error, setError] = useState<string | null>(null); const endRef = useRef<HTMLDivElement>(null);
  const setPetState = (next: PetState) => { setState(next); onStateChange?.(next); };
  useEffect(() => { if (isOpen) endRef.current?.scrollIntoView({ behavior: 'smooth' }); }, [isOpen, messages]);
  useEffect(() => { if (!isOpen) setPetState('IDLE'); }, [isOpen]);
  const send = async (value = input) => { const message = value.trim(); if (!message || !currentUser.tenantId) return; setMessages(previous => [...previous, { id: `user-${Date.now()}`, sender: 'user', text: message }]); setInput(''); setError(null); setPetState('THINKING'); try { const response = await apiRequest<PetResponse>('/api/v1/ai/pet/chat', { method: 'POST', headers: { 'X-Tenant-Id': currentUser.tenantId }, body: JSON.stringify({ message, context: { currentModule: 'workspace' } }) }); setMessages(previous => [...previous, { id: `ai-${Date.now()}`, sender: 'ai', text: response.message }]); setPetState(response.state); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'AVENQUIS Pet is unavailable.'); setPetState('ERROR'); } };
  if (!isOpen) return null;
  return <div className="fixed inset-0 z-50 flex justify-end" role="dialog" aria-modal="true" aria-label="AVENQUIS AI companion"><button aria-label="Close AI companion" onClick={onClose} className="absolute inset-0 bg-stone-900/35" /><section className="relative flex h-full w-full max-w-lg flex-col bg-[#FAF7F2] shadow-2xl"><header className="flex items-center justify-between border-b border-[#EBE6DD] bg-white p-4"><div className="flex items-center gap-3"><img src={PET_ASSETS[state]} alt="" className="h-10 w-10 object-contain" /><div><h2 className="text-sm font-bold text-[#1C1F1E]">AVENQUIS Pet</h2><p className="text-xs text-[#66736D]">Protected firm workspace · {currentUser.tenant}</p></div></div><button aria-label="Close" onClick={onClose} className="rounded-lg p-2 text-stone-500 hover:bg-stone-100"><X className="h-5 w-5" /></button></header><div className="border-b border-[#EBE6DD] bg-[#F3F8F5] px-4 py-3 text-xs text-[#285442]"><Sparkles className="mr-1 inline h-3.5 w-3.5" />Read-only companion. It only answers through the secured Pet API.</div><div className="flex flex-1 flex-col gap-3 overflow-y-auto p-4">{!messages.length && <div className="rounded-xl border border-[#D8E5DF] bg-white p-4 text-sm text-stone-700"><Bot className="mb-2 h-5 w-5 text-[#113227]" />Hello, {currentUser.name}. Ask AVENQUIS anything about your current workspace. I will not invent firm records or take actions.</div>}{messages.map(message => <div key={message.id} className={message.sender === 'user' ? 'self-end rounded-2xl bg-[#113227] px-4 py-3 text-sm text-white' : 'self-start rounded-2xl border border-[#E5DDD0] bg-white px-4 py-3 text-sm text-stone-800'}>{message.text}</div>)}{state === 'THINKING' && <div className="self-start text-sm text-[#66736D]">AVENQUIS Pet is thinking…</div>}{error && <p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div ref={endRef} /></div><div className="border-t border-[#EBE6DD] bg-white p-4"><div className="mb-2 flex flex-wrap gap-2">{['Summarize this page', 'Show my tasks', 'Show alerts'].map(action => <button key={action} onClick={() => send(action)} disabled={state === 'THINKING'} className="rounded-full border border-[#D8E5DF] px-3 py-1 text-xs font-medium text-[#285442] disabled:opacity-50">{action}</button>)}</div><form onSubmit={event => { event.preventDefault(); void send(); }} className="flex gap-2"><label className="sr-only" htmlFor="pet-message">Ask AVENQUIS</label><input id="pet-message" value={input} onChange={event => setInput(event.target.value)} placeholder="Ask AVENQUIS" className="min-w-0 flex-1 rounded-xl border border-[#D8E5DF] px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-[#C58A3E]" /><button aria-label="Send message" disabled={!input.trim() || state === 'THINKING'} className="rounded-xl bg-[#113227] p-2 text-white disabled:opacity-50"><Send className="h-5 w-5" /></button></form></div></section></div>;
};
